services:
  take-a-seat-database:
    container_name: take-a-seat-database
    restart: unless-stopped
    env_file: .env
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME_RO: ${DATABASE_USERNAME_RO}
      DATABASE_PASSWORD_RO: ${DATABASE_PASSWORD_RO}
    volumes:
      - take-a-seat-data:/var/lib/postgresql/data/
      - ./scripts/init-databases-and-users.sh:/docker-entrypoint-initdb.d/init-databases-and-users.sh
    ports:
      - '5432:5432'
    networks:
      - take-a-seat

  take-a-seat-backend:
    container_name: take-a-seat-backend
    image: ghcr.io/corentingiraud/take-a-seat:backend-latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    ports:
      - '1337:1337'
    networks:
      - take-a-seat
    depends_on:
      - take-a-seat-database
  
  take-a-seat-frontend:
    container_name: take-a-seat-frontend
    image: ghcr.io/corentingiraud/take-a-seat:frontend-latest
    restart: unless-stopped
    env_file: .env
    environment:
      NEXT_PUBLIC_STRAPI_API_URL: ${NEXT_PUBLIC_STRAPI_API_URL}
    ports:
      - '3000:3000'
    networks:
      - take-a-seat
    depends_on:
      - take-a-seat-backend

volumes:
  take-a-seat-data:

networks:
  take-a-seat:
    name: Take-a-seat
    driver: bridge
