#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create the database
    CREATE DATABASE "$DATABASE_NAME";

    -- Create full access user
    CREATE USER "$DATABASE_USERNAME" WITH PASSWORD '$DATABASE_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO "$DATABASE_USERNAME";

    -- Create read-only user
    CREATE USER "$DATABASE_USERNAME_RO" WITH PASSWORD '$DATABASE_PASSWORD_RO';

    -- Grant read-only privileges
    \connect "$DATABASE_NAME"
    GRANT CONNECT ON DATABASE "$DATABASE_NAME" TO "$DATABASE_USERNAME_RO";
    GRANT USAGE ON SCHEMA public TO "$DATABASE_USERNAME_RO";
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO "$DATABASE_USERNAME_RO";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "$DATABASE_USERNAME_RO";
EOSQL
