#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create the database
    CREATE DATABASE "$DATABASE_NAME";

    -- Create full access user
    CREATE USER "$DATABASE_USERNAME" WITH PASSWORD '$DATABASE_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO "$DATABASE_USERNAME";

    -- Connect to the new DB
    \connect "$DATABASE_NAME"

    -- Full rights on public schema
    GRANT ALL ON SCHEMA public TO "$DATABASE_USERNAME";
    GRANT CREATE ON SCHEMA public TO "$DATABASE_USERNAME";

    -- Default privileges for future objects (RW user)
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$DATABASE_USERNAME";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$DATABASE_USERNAME";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO "$DATABASE_USERNAME";

    -- Create read-only user
    CREATE USER "$DATABASE_USERNAME_RO" WITH PASSWORD '$DATABASE_PASSWORD_RO';

    -- Basic rights
    GRANT CONNECT ON DATABASE "$DATABASE_NAME" TO "$DATABASE_USERNAME_RO";
    GRANT USAGE ON SCHEMA public TO "$DATABASE_USERNAME_RO";

    -- Read-only access on existing tables
    GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA public TO "$DATABASE_USERNAME_RO";

    -- Read-only access on existing sequences
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "$DATABASE_USERNAME_RO";

    -- Default privileges for future tables/sequences (RO user)
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO "$DATABASE_USERNAME_RO";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO "$DATABASE_USERNAME_RO";
EOSQL
